### ISSUE TITLE
v4 Full Page Caching Method for WordPress Sites

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/easyengine#1015]
In EE v3, we have provided four methods. More details - https://easyengine.io/wordpress-nginx/tutorials/

1. **`--w3tc`** w3-total-cache using WordPress Plugin
2. **`--wpsc`** wp-super-cache using WordPress Plugin
3. **`--wpfc`** fastcgi-cache using Nginx core module
4. **`--wpredis`** redis-full-page backed using nginx custom modules (the main reason we were forced to maintain our own nginx build)

Now going ahead, in V4, we are planning to keep only one full page caching method. Main reasons to do are:
1. Ease of maintenance. Less code, less config. Less moving parts mean fewer issues and more stability. 
2. In all four methods, one a page is successfully cached, nginx reads it from memory without getting PHP + MySQL involved. So practically there is not much performance difference to make justify the overhead of maintaining four caching mechanism.

# Comparsion

Besides performance, there are other tradeoffs discussed in details.

## Control over what gets cached

1. WordPress plugins obviously has more control. But practically we did not run into an issue where we felt something missing using Nginx-module based methods.
2. Nginx level config has been tested over years and so far meets all practical needs.

## Cache Purging

1. `--wpredis` can support wildcard expression in purge URLs. That gives most fine-grained control over cache purging. This is implemented in the nginx-helper plugin using Lua script so even if wildcard expression translate over 1000+ URLs or cache keys, the purge is almost instant.  
2. Unfortunately, `--fastcgi` doesn't allow wildcard purge in Nginx free edition. 
3. We did not try this with WordPress plugins so can't comment on their capabilities. But both `--w3tc` and `--wpsc` write to disk so iterating a wildcard expression and deletinng 1000+ URLs is definitely going to be slow.

## Distributed Cache

1. Although EasyEngine doesn't support multi-server setup out of the box, we used it to run a site spread across multiple server. In those cases, only `--wpredis` is practical choice because we need a memory-based key/value store which can be accessed remotely.
2. Besides that redis has master-slave replication and clustering support. So based on application demands, cache can be copied locally for faster "local" access.

## Other notes

1. `--fastcgi` has a use `stale` flag. I am yet to test if something like that is possible with `--wpredis`.
2. `--wpredis` needs custom nginx build. We can use OpenResty (nginx variant) which gives all modules we need out of box. So we wont need to maintain our own nginx build.
3. **Important** We tested [batcache](https://github.com/Automattic/batcache) (a WordPress plugin) which write to memcache and then attempted to read the full page from memcache directly from Nginx. This is still work in progress. But in theory, if it works, it should give us best of both - cache control/purge that comes with WordPress plugin + distributed/scalable memcache backend.

# Questions

- [ ] Which among current four methods we should be going with? We are biased towards `--wpredis`. Does anyone has any bad experience?
- [ ] Is it fine to use OpenResty? Any experience using it?
- [ ] Did anyone use batcache with Nginx directly reading from memcache?
- [ ] In general, which one you prefer - Redis or Memcache - for key-value memory-based store?

If you need more details, please let us know share. 

We need to make a decision within a week.

**Comment by renatonascalves** [comment]
I'm already biased toward `--wpredis`. Since I started using easyengine, I always used it. I did some simple benchmarks a few years back but for personal experience, `--wpredis` has been the best option cache-wise.

One thing was common in the past was related to allocated memory. Where I needed to increase the Redis cache memory from time to time because it kept getting "full".

I don't know a lot about OpenResty so I'm not sure if it is a good option. I think I read a few articles talking good things about it a few months ago. But if it does what Nginx does and it eases the maintenance burden, I support the change.

Al in all, I prefer Redis for the same reasons you mentioned here.

**Comment by centminmod** [comment]
@rahul286 I don't use EasyEngine but as one LEMP stack developer to another, just a few suggestions from my experience :)

1. I'd avoid using memcached caching for full page caching as it still has a 250 max character key length limit and if your wordpress url's are non-English characters you can possible run into the KEY_MAX_LENGTH = 250 baked into memcached servers. Redis would be a much easier backend to work with and it's easy to even setup multiple redis servers if needed.

within memcached 1.5.8 source code 
```
grep -n 'KEY_MAX_LENGTH' memcached.h
36:#define KEY_MAX_LENGTH 250
```

2. Openresty is awesome, I use alot of their nginx modules in my own custom Centmin Mod LEMP stack's Nginx builds. But if you look at the history of Openresty as a whole, their Nginx version update timelines can be slower than what some would be comfortable with as they have to ensure full compatibility and testing with all their Openresty modules.

3. Oh if you choose redis caching, any plans to update nginx-helper wp plugin to support redis unix sockets - might want add that to a 'to do' list :)

Just my AUD$0.02 :) Good Luck !

**Comment by rahul286** [comment]
@pjv 

> downside for some users might be an inability to easily run redis server for whatever reason.

Was it a general comment or EasyEngine specific? We haven't come across a single issue where EasyEngine couldn't install redis (EE supposed to do it automatically without user need to take any action)

> batcache + memcache

We will consider Memcache only if batcache works. The team did some initial test, and they found it ran into issues. I will try again.

>openresty

The `--wpredis` caching method uses multiple nginx modules developed by and maintained by the openresty team. 
___

@renatonascalves 

> redis cache getting full

It might be because of cache fragmentation unless the site in which you faced issue was too many and probably big pages.

___


@centminmod Thanks a lot for your inputs. Your experience is priceless! 🙇 

> memcache limit

Thanks. We need to use URLs as it is as keys to make wildcard purging possible. 

This also reminds me that the speed at which we purge multiple keys from redis (using https://redis.io/commands/eval ) may not be possible with memcache. (memcache has [delete by namespace](https://github.com/memcached/memcached/wiki/ProgrammingTricks#deleting-by-namespace) which is slower and less flexible) 

> nginx-helper

It will be rewritten completely as there will be only one caching method with some advanced options, e.g. wildcard purging. 

We are internally discussing if we should rewrite nginx-helper or release a new plugin. The way WordPress updates work, there is a chance that somebody might update plugin casually and if they are using nginx-fastcgi-cache, then there cache purging might break. 

Do you see any major benefits in using redis with unix socket compared to TCP/IP? We kept TCP/IP as default because we often use a separate VPS for redis-cache or sometimes Amazon ElasticCache.

**Comment by pjv** [comment]
>Was it a general comment or EasyEngine specific? We haven't come across a single issue where EasyEngine couldn't install redis (EE supposed to do it automatically without user need to take any action)

general - i was thinking about people with low-mem servers who might be able to use nginx fast cache but don't have enough ram to use redis.

>We are internally discussing if we should rewrite nginx-helper or release a new plugin. The way WordPress updates work, there is a chance that somebody might update plugin casually and if they are using nginx-fastcgi-cache, then there cache purging might break.

definitely +1 for new plugin. maybe should be called ee-companion or something like that. I actually started writing it myself last year, but got sidetracked on other projects and never found my way back to it yet.

**Comment by michacassola** [comment]
I also vote for --wpredis.

**Comment by eddr** [comment]
1. W3TC has problems, but it has multiple functionalities and is maintained. One such functionality is the object cache that worked for me the best and had less problems. maybe because the implementation is better or perhaps because the ecosystem is better and other plugins/WP itself take it into account.

2. Emphasis on **object cache** is important for those who have a more dynamic site, like a very active forum, which currently means it does go via PHP(unless you keep lots of versions for each page).  A good redis/memcache implementation can handle it though, it just have to be tested

3. Saving all pages in memory isn't a bit wasteful? Anyway, if eventually page cache will be saved in RAM, then perhaps it's better to make sure **the compressed version is saved**

4. Do we know batcache maintenance is reliable?

**Comment by centminmod** [comment]
@rahul286 

> We are internally discussing if we should rewrite nginx-helper or release a new plugin. The way WordPress updates work, there is a chance that somebody might update plugin casually and if they are using nginx-fastcgi-cache, then there cache purging might break.

Yeah probably better to have separate plugin maybe `nginx-redis-helper` so as to not break `nginx-helper` fastcgi_cache users WP instances.

> Do you see any major benefits in using redis with unix socket compared to TCP/IP? We kept TCP/IP as default because we often use a separate VPS for redis-cache or sometimes Amazon ElasticCache.

Redis unix sockets can be up to 50% faster than TCP defaults for local Redis server usage.  Though with current Kernel KPTI/Meltdown/Spectre patching we already loose some Redis performance these days heh.

But yes if you need remote Redis server then TCP only way. Though technically without native encryption in current Redis server (Redis folks are working on native encryption though), you'd have to use some form of encryption layer between remote Redis server anyway i.e. stunnel'd redis connection and then Redis performance drops dramatically with standard Redis stunnel with rsa 2048bit ssl. Though you can boost Redis stunnel encrypted performance by 50% with ecdsa 256bit TLS1.3 based setup - benchmarks https://github.com/centminmod/centminmod-stunnel. Using a separate Redis server for performance reasons becomes pretty much moot when you introduce an encrypted stunnel layer into remote Redis server communication channel. Unless you're using a remote Redis server for reasons other than solely performance.

Linode, DigitalOcean, Vultr and SSDnodes cloud/vps providers all provide plans with ample memory these days so really no reason not to use Redis locally rather than to offload redis server externally :)  Though I can see it could be problematic for some folks who have limited memory - where having static html caching plugins like wp super cache/keycdn cache enabler would be better. But if you plan to use composer which can potentially require alot of memory up to 1.5GB even, then folks will have get use to the higher memory requirements anyway.

**Comment by rahul286** [comment]
@centminmod 

> unix vs tcp/ip

May I know how did you benchmark? A few years ago, we did some testing where we found Unix sockets were faster but TCP/IP could handle more parallel requests. 

We did testing between nginx fastcgi and php-fpm upstream. Of course, our testing could be flawed as there could be other things affecting results.

> not using redis locally

The default is local redis only. We put redis on a separate instance when using multiple servers in behind load-balancers. In these cases, it acts as a shared-cache so cache-HIT improves.

> encryption

I would not mind leaving page cache unencrypted as the content in page-cache is any way public. Although encryption is a must for WordPress object-cache.

In all external redis setup we did, in most cases, redis was accessible within local network or VPN only. When using external access, we used [redis AUTH](https://redis.io/commands/auth).

I felt redis performance degrade a lot faster when moved from local > remote. 

> low memory

We tested redis local cache server on 512MB DO and it went smooth. 

The idea is - for WordPress sites we will need Memcache or Redis anyway for the object-cache backend. Then why not use same memory store backend and have additional features like wildcard purging, shared-cache support in a multi-server setup.

I believe putting content in memory directly won't take extra RAM for storage as [Nginx open_file_cache](http://nginx.org/en/docs/http/ngx_http_core_module.html#open_file_cache ) and OS will likely cache frequently access cache files' metadata/content in memory. The additional overhead could be RAM and CPU needed for Redis process itself. But then these processes would anyway be running for object-cache where it provides tangible benefits already.

When we created [redis based full-page](https://easyengine.io/blog/easyengine-3-3-full-page-redis-cache/) cache mechanism a few years ago, I felt it was hackish and may not survive with time. But surprisingly it worked a lot better. 

As now we are moving to OpenResty rather than maintaining custom nginx build and keeping one caching solution only, things should be better.

**Comment by pjv** [comment]
>The idea is - for WordPress sites we will need Memcache or Redis anyway for the object-cache backend. Then why not use same memory store backend and have additional features like wildcard purging, shared-cache support in a multi-server setup.

definitely seems better to avoid the additional overhead, maintenance, and attack surface to avoid having two separate backends when one or the other can do both jobs. I haven't paid any attention to memcache development for a few years since i switched to redis, so i don't know what's up there, but redis development seems like it is full-steam ahead.

btw, i am using [this redis object caching plugin](https://wordpress.org/plugins/redis-cache/) from @tillkruss. I contributed some selective flushing code to it inspired by the little lua script in nginx-helper that does the wildcard page cache flushing. The selective flush lets you flush all objects where the key is prefixed by the key salt string which should be different for each wp site on a server that hosts multiple sites. this allows you to flush the cache for a particular site without flushing other sites objects (and the whole page cache too).

>Redis unix sockets can be up to 50% faster than TCP defaults for local Redis server usage. Though with current Kernel KPTI/Meltdown/Spectre patching we already loose some Redis performance these days heh.

wow, if that benchmark is for real, i need to try it on my servers. I'm using local redis only. @centminmod can you point me to some good docs for setting up the sockets in redis and accessing them from nginx configs.

**Comment by centminmod** [comment]
> May I know how did you benchmark? A few years ago, we did some testing where we found Unix sockets were faster but TCP/IP could handle more parallel requests.
> 
> We did testing between nginx fastcgi and php-fpm upstream. Of course, our testing could be flawed as there could be other things affecting results.

Benchmarks done with redis nginx level setup (nginx upstream and nginx tcp stream configs) and redis-benchmark tests via my Centmin Mod LEMP stack tool, [redis-generator.sh](https://github.com/centminmod/centminmod-redis) to generate different/multiple redis server configurations. i.e. https://github.com/centminmod/centminmod-redis/blob/master/examples/redis-proxy-benchmarks-160317.md (TCP though in that test).

You're talking about unix socket config stress/load tests hitting = `Resource temporarily unavailable (errno=11)` errors right ? Somewhat true for php-fpm unix sockets but redis unix sockets performs better than TCP compared to php-fpm unix sockets. But ultimately depends on how your OS system configures your datagram queue length (`net.unix.max_dgram_qlen`) as it varies depending on OS and even OS version and virtualisation type i.e. openvz won't be able to tune such.  For Centmin Mod, I currently auto tune datagram queue length for CentOS 7 (eventually will do same for CentOS 6) and non-openvz systems on initial installation to allow unix sockets to scale better :)

> wow, if that benchmark is for real, i need to try it on my servers. I'm using local redis only. @centminmod can you point me to some good docs for setting up the sockets in redis and accessing them from nginx configs.

The default redis.conf usually has commented out section for unix socket, just uncomment those 2 lines and set appropriate permissions http://download.redis.io/redis-stable/redis.conf but there may other OS dependent changes needed for where you place that unix socket and it's permissions. I don't use Ubuntu/Debian as I am a CentOS user so I place it at `/var/run/redis/redis.sock`. 

For nginx accessing unix sockets it's same as php-fpm unix sockets via a nginx upstream or nginx TCP upstream context config and defined in redis_pass and redis2_pass directives to use those upstreams i.e. [nginx TCP upstream proxy](https://github.com/centminmod/centminmod-redis/blob/master/examples/redis-proxy-benchmarks-160317.md). Only limit in context of wordpress usage is that current nginx-helper doesn't support unix sockets https://github.com/rtCamp/nginx-helper/issues/121 but guess that will be changing ^_^

Though Unix sockets in some cases is only a minor improvement over TCP in terms of throughput reqs/s but latency response time is also better with Unix sockets even if throughput doesn't improve much i.e. when i tested [Magento 2 Redis full page cache with TCP vs Unix sockets](https://github.com/centminmod/centminmod-magento2#magento-2-redis-benchmarks).

FYI, **Redis can be configured to listen on both TCP and Unix sockets at the same time** so you can switch between TCP and Unix sockets depending on what your app supports so really not much extra effort involved on redis server side in having both redis TCP + Unix socket supported. It doesn't haven't to be a choice of either TCP mode or Unix socket mode. Just a matter of application/wp plugin side being able to support both. And if it ain't obvious yet, looking forward to some version of nginx-helper support redis unix sockets + TCP modes ^_^  

With ephemeral ports exhaustion a reality, there's only so much you can do TCP concurrent load wise. So offloading some of that to Unix sockets would be an option too. If each individual server is optimised and tuned to scale and perform better by themselves, then the necessity of using load balanced configs lessens (the longer that single server config can remain in operation) and/or number of load balanced servers required lessens :)

**Comment by rahul286** [comment]
@centminmod 

> Redis can be configured to listen on both TCP and Unix sockets at the same time

This is priceless! I did not know about it. Seems like a good idea to keep both options enabled. :)

**Comment by michacassola** [comment]
Isn't the discussion about the v4 Full Page Caching Method for WordPress Sites done?
The rest of the subject here is just about Redis details, but the original Issue could be closed as we will only have `--wpredis`

**Comment by mbtamuli** [comment]
@michacassola Yes. We can close this issue. 

We have already implemented `--wpredis` in 4.0.0-beta.1 itself. @everyone thank you for giving your inputs.

**Comment by pserafini** [comment]
Quick question : how about dynamic caching when using wp-redis ? A lot of wordpress users might need it for adserving or this kind of things.

**Comment by M0opex** [comment]
Hello, 
My cache tag is like, cache-control: no-cache, must-revalidate, max-age=0

How I can make edits on this header, using the last version of easyengine

thanks

**Comment by osevan** [comment]
We need wptarantool

https://stackoverflow.com/questions/36186137/how-would-tarantool-be-embedded-inside-openresty


Full page caching inside nginx with tarantool upstream module.
