### ISSUE TITLE
Have consolidated documentation for v4

### ISSUE THREAD

**Issue by kirtangajjar** [EasyEngine/easyengine#1084]
We currently do have some docs for v4 - 
https://github.com/EasyEngine/easyengine/tree/develop-v4/docs

But we also need it to be accessible to people via github pages or wiki or from our easyengine website.

**Comment by brianjking** [comment]
@kirtangajjar -- I'm happy to help out with this. I would suggest using one of the following and am happy to get started once you let me know what the rest of the EasyEngine team decides on. 

* Using [MkDocs](https://github.com/mkdocs/mkdocs) with the [MkDocs Material](https://squidfunk.github.io/mkdocs-material/) theme and hosting on GitHub Pages.

* Using [SphinxDoc](http://www.sphinx-doc.org/en/stable/index.html) with [ReadTheDocs](https://readthedocs.org/) for building & hosting the docs.

Sphinx is a bit more complicated as `reStructuredText` isn't as widely understood as `Markdown` so contributing has a bit larger barrier to entry. However, it would also provide EasyEngine with the option to download a `PDF` and/or `ePUB` file for offline access and archiving.


cc: @rahul286 & @rahulsprajapati @rtCamp

**Comment by rahul286** [comment]
@brianjking any reason to recommend MkDocs? 

Among static site generators, I prefer [Hugo](https://gohugo.io/), [Gitbook](https://www.gitbook.com/) and also [Jekyll-Github-Pages](https://help.github.com/articles/about-github-pages-and-jekyll/).

Ideally, I would like to setup sync between a WordPress site and Github repo. May be using something like https://github.com/mAAdhaTTah/wordpress-github-sync

**Comment by brianjking** [comment]
@rahul286 --

* MkDocs is nice as editing content/creating new content requires just basic `Markdown` knowledge. It can be hosted for free on GitHub Pages, [MkDocs Material](http://squidfunk.github.io/mkdocs-material/) theme is clean, responsive, has built in translation support, syntax highlighting, is version controlled, no hosting expenses or maintenance necessary as there would be with WordPress, it's made for writing documentation and IMO it does this very well.

    * As EasyEngine (and most other open source projects) suffer from lack of donations/income/sponsorship/volunteer time adding something such as WordPress seems to just add unnecessary maintenance and expenses. 

* Hugo & Jekyll are nice, however, I have less experience with either of these. I believe there is a port of the MkDocs Material theme for Hugo, however, it might be slightly out of date from my quick glance a few minutes ago [here](https://github.com/digitalcraftsman/hugo-material-docs).

* Gitbook is nice and definitely would be far more appealing to me than Hugo or Jekyll. It's easy to browse on computer, responsive for mobile, and has `PDF` and `ePUB` generation similar to what is generated with [SphinxDoc](http://www.sphinx-doc.org/en/stable/index.html) when using [ReadTheDocs](https://docs.readthedocs.io/en/latest/index.html).

Gitbook is limited to [2 users](https://www.gitbook.com/pricing) on the free plan. However, it looks like they have a free to use for non-profit & open source projects. 

Let me know your thoughts...



cc: @kirtangajjar @rtCamp @rahulsprajapati

**Comment by brianjking** [comment]
Any updates on this? Still available and would like to help contribute on these docs.

For a project that seems to suffer primarily from lack of volunteers who are actually looking to contribute code, support, or documentation this certainly hasn't been easy.

CC: @rahul286 @mbtamuli @kirtangajjar @rtCamp @rahulsprajapati

**Comment by rahul286** [comment]
@brianjking I read https://docs.gitbook.com/v2-changes/important-differences and its seriously limiting. They are basically saying they discontinued whole thing!

Gitbook no longer uses git! No markdown etc. Better than calling it V2, they should have launched a new product IMHO.

At the moment, we are planning to use Github Pages and Jekyll only. The documentation work is yet to start https://github.com/EasyEngine/easyengine.github.io

We are really low on resources (or put it other way have a lot to work on than our team of 4-5 people can do!) :/

**Comment by brianjking** [comment]
@rahul286 -- This is why I'm saying I can help out with docs as your core team is overloaded with work...

**Comment by rahul286** [comment]
@brianjking You are more than welcome to help. How would you prefer to start? I mean do you need an outline of docs/content, or something else.

**Comment by brianjking** [comment]
@rahul286 -- I'd need whatever you have in terms of docs/content for the v4 release. I'd really prefer to move forward with MkDocs over Jekyll, seems just much more straightforward.

**Comment by mbtamuli** [comment]
I've setup this repo. Using GitBook.
https://github.com/EasyEngine/easyengine.github.io -> https://easyengine.github.io/
Will be adding documentation in a day or two.

**Comment by mbtamuli** [comment]
We can generate PDF for offline access - https://toolchain.gitbook.com/ebook.html,
and we can have multi language support - https://toolchain.gitbook.com/languages.html

Will have to look into it. Will create issues once this is set up, and will ping you @brianjking for help if you still want to help. :slightly_smiling_face:

**Comment by brianjking** [comment]
@mbtamuli  

I thought based on @rahul286's comments [here](https://github.com/EasyEngine/easyengine/issues/1084#issuecomment-412975801) from 8 days ago and my comments from [28 days ago](https://github.com/EasyEngine/easyengine/issues/1084#issuecomment-407909329) that GitBook isn't a good option since it's no longer using git, no longer generates PDF (in v2), no longer using Markdown and instead is using AsciiDoc....

* [V2 changes](https://docs.gitbook.com/v2-changes/important-differences)

![image](https://user-images.githubusercontent.com/6786817/44473946-199c9f00-a5f7-11e8-96e8-b6d442b7eb7c.png)


cc: @rahul286 @kirtangajjar @rtCamp @rahulsprajapati

**Comment by mbtamuli** [comment]
@brianjking  If you see here - https://github.com/GitbookIO/gitbook#publish-your-book it mentions [legacy.gitbook.com](https://legacy.gitbook.com/) as _Heroku for books_. As such, the changes mentioned here - https://docs.gitbook.com/v2-changes/important-differences, pertaining to [docs.gitbook.com](https://docs.gitbook.com) which is an upgrade from [legacy.gitbook.com](https://legacy.gitbook.com/), is the hosted platform itself.

We're using GitBook CLI - https://github.com/GitbookIO/gitbook, and our purpose will be served in bringing documentation to the users. GitBook CLI documentation is at - https://toolchain.gitbook.com/ and it contains all the features that I mentioned https://github.com/EasyEngine/easyengine/issues/1084#issuecomment-415067699. 

You can think of [GitBook](https://www.gitbook.com/) vs [GitBook CLI](https://toolchain.gitbook.com/) as the same difference as Git vs GitHub

Also, if your concern is that someone wishing to contribute to the docs will have to use the git command line, they can simply use GitHub and edit markdown files directly, or we can configure the edit links to point to https://prose.io/ so that we have a proper Markdown editor.

**Comment by brianjking** [comment]
@mbtamuli Yeah, I understand the differences between GitBook v2 and GitBook Legacy. 

How can I help contribute to these docs in the repository you've setup [here](https://github.com/EasyEngine/easyengine.github.io)?


@rahul286 Perhaps you can help out as well as per your comment [6 days ago](https://github.com/EasyEngine/easyengine/issues/1084#issuecomment-414769399)?

Thanks...

**Comment by rahul286** [comment]
@brianjking sorry for a delayed reply.

We have started documentation here https://github.com/EasyEngine/docs#v4-docs

The README has all details to get you started including the link to topics we like to document - https://github.com/EasyEngine/docs/issues?q=is%3Aissue+is%3Aopen+label%3Adocumentation

I am closing this issue. If you need any input, we can start a disucssion in docs repo. :-)

**Comment by brianjking** [comment]
@rahul286 https://twitter.com/brianjking/status/1067864888041566208

**Comment by rahul286** [comment]
@brianjking since you prefer Twitter, posted reply on Twitter.
