### ISSUE TITLE
Unable to create more than 29 sites

### ISSUE THREAD

**Issue by kirtangajjar** [EasyEngine/easyengine#1244]
Currently in v4 we won't be able to create more than 29 sites(unless some are disabled). This is because docker is unable to find new IP address to allocate - https://loomchild.net/2016/09/04/docker-can-create-only-31-networks-on-a-single-machine/

There is still a way around it(by manually specifying subnet during network create) and we need to check how to implement it.

**Comment by mbtamuli** [comment]
For this issue, we have decided that currently, we'll go with a workaround of just allowing users to create a limited number of sites, 27 to be precise. 
We might fix this in the future and since shared hosting is not high on the priority list for EasyEngine, this is something that might not be worked on soon. If someone is interested in actually working on fixing this issue, I would be glad to help with the implementation details.
