### ISSUE TITLE
--no-prompt not working with ee site delete sitename

### ISSUE THREAD

**Issue by devbhosale** [EasyEngine/easyengine#1258]
This issue tracker is only for issues related to EasyEngine. Please use http://community.rtcamp.com/c/easyengine for support questions.

running
sudo ee site delete ee1.MYDOMAIN --no-prompt
Are you sure you want to delete ee1.mycontent.top? [y/n]

If you feel the issue is a EasyEngine core specific issue, please attach the output of the following commands.

System Information
- [ ] lsb_release -a
Ubuntu 18.04.1 LTS
- [ ] ee cli version
EE 4.0.0-beta.6
- [ ] ee cli info
+-------------------+----------------------------------------------------------------------------+
| OS                | Linux 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 |
| Shell             | /bin/bash                                                                  |
| PHP binary        | /usr/bin/php7.2                                                            |
| PHP version       | 7.2.11-2+ubuntu18.04.1+deb.sury.org+1                                      |
| php.ini used      | /etc/php/7.2/cli/php.ini                                                   |
| EE root dir       | phar://ee.phar                                                             |
| EE vendor dir     | phar://ee.phar/vendor                                                      |
| EE phar path      | /home/sspadmin/ee-sites                                                    |
| EE packages dir   |                                                                            |
| EE global config  | /opt/easyengine/config.yml                                                 |
| EE project config |                                                                            |
| EE version        | 4.0.0-beta.6     
- [ ] wp --allow-root --info
not found

**Comment by mrrobot47** [comment]
@devbhosale This is an entirely a new version of EasyEngine, so the parameters for usage have been changed a little. As far as the backward compatibility is concerned, the `site create` parameters of EEv3 are accepted in EEv4. Apart from that there are slight changes in the parameters for other commands.

Until the documentation is completely prepared and launched, you can use `ee help <command-name>` or `ee help <command-name> <sub-command-name>`, in your case you can use `ee help site delete` for more info, for [site delete specifically](https://github.com/easyengine/site-command#ee-site-delete) instead of `--no-prompt`, the new flag is `--yes` to skip the prompt.

Also, for other ee subcommands you can browse throught their README in each case or use `ee help` for more info. All the sub-commands have thier own repo. It would be helpful for us if you open issues regarding a particular command in it's own repo. You can browse through [here](https://github.com/easyengine/) to view all the command repos. Thank You, keep reporting issues, we would love to resolve them as soon as possible.

**Comment by mrrobot47** [comment]
@devbhosale This is an entirely a new version of EasyEngine, so the parameters for usage have been changed a little. As far as the backward compatibility is concerned, the `site create` parameters of EEv3 are accepted in EEv4. Apart from that there are slight changes in the parameters for other commands.

Until the documentation is completely prepared and launched, you can use `ee help <command-name>` or `ee help <command-name> <sub-command-name>`, in your case you can use `ee help site delete` for more info, for [site delete specifically](https://github.com/easyengine/site-command#ee-site-delete) instead of `--no-prompt`, the new flag is `--yes` to skip the prompt.

Also, for other ee subcommands you can browse throught their README in each case or use `ee help` for more info. All the sub-commands have thier own repo. It would be helpful for us if you open issues regarding a particular command in it's own repo. You can browse through [here](https://github.com/easyengine/) to view all the command repos. Thank You, keep reporting issues, we would love to resolve them as soon as possible.

**Comment by mrrobot47** [comment]
@devbhosale This is an entirely a new version of EasyEngine, so the parameters for usage have been changed a little. As far as the backward compatibility is concerned, the `site create` parameters of EEv3 are accepted in EEv4. Apart from that there are slight changes in the parameters for other commands.

Until the documentation is completely prepared and launched, you can use `ee help <command-name>` or `ee help <command-name> <sub-command-name>`, in your case you can use `ee help site delete` for more info, for [site delete specifically](https://github.com/easyengine/site-command#ee-site-delete) instead of `--no-prompt`, the new flag is `--yes` to skip the prompt.

Also, for other ee subcommands you can browse throught their README in each case or use `ee help` for more info. All the sub-commands have thier own repo. It would be helpful for us if you open issues regarding a particular command in it's own repo. You can browse through [here](https://github.com/easyengine/) to view all the command repos. Thank You, keep reporting issues, we would love to resolve them as soon as possible.

**Comment by mrrobot47** [comment]
@devbhosale This is an entirely a new version of EasyEngine, so the parameters for usage have been changed a little. As far as the backward compatibility is concerned, the `site create` parameters of EEv3 are accepted in EEv4. Apart from that there are slight changes in the parameters for other commands.

Until the documentation is completely prepared and launched, you can use `ee help <command-name>` or `ee help <command-name> <sub-command-name>`, in your case you can use `ee help site delete` for more info, for [site delete specifically](https://github.com/easyengine/site-command#ee-site-delete) instead of `--no-prompt`, the new flag is `--yes` to skip the prompt.

Also, for other ee subcommands you can browse throught their README in each case or use `ee help` for more info. All the sub-commands have thier own repo. It would be helpful for us if you open issues regarding a particular command in it's own repo. You can browse through [here](https://github.com/easyengine/) to view all the command repos. Thank You, keep reporting issues, we would love to resolve them as soon as possible.

**Comment by mrrobot47** [comment]
@devbhosale This is an entirely a new version of EasyEngine, so the parameters for usage have been changed a little. As far as the backward compatibility is concerned, the `site create` parameters of EEv3 are accepted in EEv4. Apart from that there are slight changes in the parameters for other commands.

Until the documentation is completely prepared and launched, you can use `ee help <command-name>` or `ee help <command-name> <sub-command-name>`, in your case you can use `ee help site delete` for more info, for [site delete specifically](https://github.com/easyengine/site-command#ee-site-delete) instead of `--no-prompt`, the new flag is `--yes` to skip the prompt.

Also, for other ee subcommands you can browse throught their README in each case or use `ee help` for more info. All the sub-commands have thier own repo. It would be helpful for us if you open issues regarding a particular command in it's own repo. You can browse through [here](https://github.com/easyengine/) to view all the command repos. Thank You, keep reporting issues, we would love to resolve them as soon as possible.

**Comment by mrrobot47** [comment]
@devbhosale This is an entirely a new version of EasyEngine, so the parameters for usage have been changed a little. As far as the backward compatibility is concerned, the `site create` parameters of EEv3 are accepted in EEv4. Apart from that there are slight changes in the parameters for other commands.

Until the documentation is completely prepared and launched, you can use `ee help <command-name>` or `ee help <command-name> <sub-command-name>`, in your case you can use `ee help site delete` for more info, for [site delete specifically](https://github.com/easyengine/site-command#ee-site-delete) instead of `--no-prompt`, the new flag is `--yes` to skip the prompt.

Also, for other ee subcommands you can browse throught their README in each case or use `ee help` for more info. All the sub-commands have thier own repo. It would be helpful for us if you open issues regarding a particular command in it's own repo. You can browse through [here](https://github.com/easyengine/) to view all the command repos. Thank You, keep reporting issues, we would love to resolve them as soon as possible.

**Comment by mrrobot47** [comment]
@devbhosale This is an entirely a new version of EasyEngine, so the parameters for usage have been changed a little. As far as the backward compatibility is concerned, the `site create` parameters of EEv3 are accepted in EEv4. Apart from that there are slight changes in the parameters for other commands.

Until the documentation is completely prepared and launched, you can use `ee help <command-name>` or `ee help <command-name> <sub-command-name>`, in your case you can use `ee help site delete` for more info, for [site delete specifically](https://github.com/easyengine/site-command#ee-site-delete) instead of `--no-prompt`, the new flag is `--yes` to skip the prompt.

Also, for other ee subcommands you can browse throught their README in each case or use `ee help` for more info. All the sub-commands have thier own repo. It would be helpful for us if you open issues regarding a particular command in it's own repo. You can browse through [here](https://github.com/easyengine/) to view all the command repos. Thank You, keep reporting issues, we would love to resolve them as soon as possible.
