### ISSUE TITLE
ee site create with --skip-content does not set permissions for plugins folder

### ISSUE THREAD

**Issue by petebytes** [EasyEngine/easyengine#1332]
If you use site create with --skip-content you will not have permissions to upload plugins.

System Information
- [x] ee cli info
```
+-------------------+----------------------------------------------------------------------------+
| OS                | Linux 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 |
| Shell             | /bin/bash                                                                  |
| PHP binary        | /usr/bin/php7.2                                                            |
| PHP version       | 7.2.12-1+ubuntu18.04.1+deb.sury.org+1                                      |
| php.ini used      | /etc/php/7.2/cli/php.ini                                                   |
| EE root dir       | phar://ee.phar                                                             |
| EE vendor dir     | phar://ee.phar/vendor                                                      |
| EE phar path      | /root                                                                      |
| EE packages dir   |                                                                            |
| EE global config  | /opt/easyengine/config/config.yml                                          |
| EE project config |                                                                            |
| EE version        | 4.0.3                                                                      |
+-------------------+----------------------------------------------------------------------------+
```
- [x] lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
- [x] docker version
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
- [x] docker-compose version
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

**Comment by mrrobot47** [comment]
>If you use site create with --skip-content you will not have permissions to upload plugins.

Not exactly. The permissions of the files are properly set. You can check the permissions using `ee shell <site-name>` and then doing `ls -al` or in single command `ee shell <site-name> --command='ls -al'`. It is just that `wp-content/plugins` and `wp-content/themes` folder is not created, which is causing this issue.

Which is why uploading or installing them through the dashboard fails. Although if you do `ee shell <site-name> --command='wp plugin install nginx-helper --activate'` it works.

To make it work using dashboard, simply create the directories using `ee shell <site-name> --command='mkdir -p wp-content/plugins wp-content/themes'`.

Please note that `--skip-content` is a `wp-cli` flag that we have respected in `site-type-wp`, Issue ref: https://github.com/EasyEngine/easyengine/issues/1029
Documentation of wp-cli about the same: https://developer.wordpress.org/cli/commands/core/download/#options

This is the deafult behaviour of `wp-cli` when you pass `--skip-content` to `wp core download`. It is not EasyEngine specific.
