### ISSUE TITLE
Error: could not find driver

### ISSUE THREAD

**Issue by tenil** [EasyEngine/easyengine#1403]
For each command I am getting "Error: could not find driver".

**ee cli info
Error: could not find driver**

**ee site list
Error: could not find driver**

System Information
- [X] ee cli info
`Error: could not find driver`
- [X] lsb_release -a
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
```
- [X] docker version
```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:40:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false
```

```
Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- [x] docker-compose version
```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Comment by UmeshSingla** [comment]
Facing a similar problem, also while migration EE should add a check for PHP 7.2 by default and rather give a early warning instead of telling later that EE needs at least PHP 7.2 to run.

**Comment by rickbsgu** [comment]
Is there a solution to this?

**Comment by lucianobapo** [comment]
Is there a solution to this?

**Comment by stepaola** [comment]
Is there a solution to this?

**Comment by maiChuong** [comment]
With the same problem after installing the easyengine using the following commands:
$ wget -qO ee rt.cx/ee4 && sudo bash ee #!Also the Ubuntu 16.04.6 is the linux in use.

Above line is the bash or shell script to automatically check default / global php version in linux,
making sure you set the global php version to at least php version 7.2 before you run installation.
Otherwise, you have to run the script after manually changing the php version again to let 
easyengine knows where the php.ini and the php version is!

Here is the step to check how many manually PHP versions installed in your system.
$ sudo update-alternatives --display php  #!To list PHP version use.
$ php -v #!To check current default version use command
$ sudo update-alternatives --config php #!To set default version of PHP use.

Make sure port 80 and port 443 is not in use by any services, easyengine works best on a clean server setup.

**Comment by kirtangajjar** [comment]
I think this problem is occurring when the user already has PHP installed. At that time, even if EasyEngine installs PHP, it is not being used. Default PHP of user is being used which may not have required PHP extensions (pcntl, curl, sqlite3, zip). I think we need to use `update-alternatives` to ensure that our version of PHP is being used.

Thank you everyone for reporting and bumping this issue.

cc @mrrobot47 @dhsathiya

**Comment by kirtangajjar** [comment]
This issue is tracked further at https://github.com/EasyEngine/installer/issues/31. Closing this one.

**Comment by awps** [comment]
Here's what I did on Ubuntu 22: 
```sh
apt-get upgrade # this may be ommited, I think
apt-get update
apt install php-cli php8.1-cli 
wget -qO ee rt.cx/ee4 && sudo bash ee
```

✌️
