### ISSUE TITLE
php5-fpm pools (shared-hosting model)

### ISSUE THREAD

**Issue by andremacola** [EasyEngine/easyengine#150]
Is it possible to determine/create php pools for each site? I would like to run every site with custom users and groups and not all with www-data

like: ee site create mysite.com --wp --umyuserr:gmygroup

Then ee create the php-fpm .conf file and the user:group.

I'm doing this manually every time.

**Comment by xavivars** [comment]
The problem I see with sharing www-data group is, if I'm not wrong, a php file in /home/bill/a.php could do something like "echo file_get_contents('/home/tom/b.php')" and it would work.

Change b.php with wp-conf.php and you'll see the problem.

**Comment by jeffwidman** [comment]
@xavivars That problem can be avoided by setting up separate PHP-FPM pools with different users. 

So basically `bill/a.php` is owned by `bill:nginx` and `tom/b.php` is owned by `tom:nginx`. Do not add users bill or tom to the nginx group. Nginx can see everything, but the way Nginx works,when it actually executes PHP, it does so by handing it off to PHP-FPM. 

Within PHP-FPM, you can designate that all php scripts in Bill's folder are run as user "bill" and tom's scripts are executed as user Tom. So when you try to execute echo file_get_contets, Linux file permissions will say "user Bill can't access user tom's files, and they don't share a common group either."

**Comment by apag96** [comment]
This enhancement, in my opinion, needs to be priority #1 for the EasyEngine team. Wordpress is a gaping security hole. Add some plugins in, and you're begging to get your site compromised.

I'm scared to host more than one site with EasyEngine. If one gets infected, they all are accessible (They all run under www-data's access). I put a c99 shell on one of my sites to see what someone could do if they broke in... Full and unrestricted access to all other websites. Terrifying.

**Comment by gagan0123** [comment]
I deal with clients who are running multiple WordPress sites, which they're running on a large server using WHM. Whenever I even try to get them to nginx, they only have one question, if one site gets infected, would it affect the other sites or not. Also, lets say, I put each site on a different server, then as system admin, I'll have to go through updating each server, which is going to consume a lot of time.

With shared hosting model, I will only have to take care of a single large server hosting multiple sites, and each site, in theory, should not be able to access other site's data/files. Now if we add users to the same group, then there's going to be a problem, with group permissions, they can read each other's files, which mean, any user can read wp-config.php of any other user's site, and can simply modify it to have his/her content.

All the servers I've dealt with, using WHM are running on CentOS, and here's how it works
Apache runs with user "nobody" 
It starts the php for executing any php script with the user that php file belongs to
public_html folder under each user has owner like user:nobody
but user does not belong to the group nobody, therefore cannot access other user's files.
but since public_html is belonging to the group nobody, apache can access it to serve static files when it is run by user nobody.

The longer we go without implementing this, the more time its going to take to implement.

**Comment by bigwilliam** [comment]
I agree. This issue should be priority #1. From a security angle, this is a bug, not a feature. Do we have this attached to a milestone yet?

**Comment by apag96** [comment]
I haven't seen it yet. I'm glad this is finally getting some attention
again. I've been checking daily for this feature (or bug fix) to be implied.

**Comment by gagan0123** [comment]
Just finished testing a few scenarios, mentioning the one that seems to be working fine.

nginx to be run by user www-data (its worker process and the cache manager main process is run by root which spawns these processes)

**ee site create example.com --php**  Algorithm 
create directory /var/www/example.com/
create user example-com
remove directory /home/example-com/
set example-com's home directory /var/www/example.com/
*don't add example-com to group www-data*
create directories htdocs, logs under
chown -R example-com:www-data /var/www/example.com/
find /var/www/example.com/ -type f|xargs -I file chmod 640 file
find /var/www/example.com/ -type d|xargs -I file chmod 750 file
create php-fpm pool for this user
write the site's nginx config with the newly created php-fpm pool(right now php-fpm pool is in a common conf file will have to move it from there)


Now the nginx can read all these directories to fetch the static content and send without having to invoke php-fpm. 
php-fpm will be running the script via that user, so theoretically, it should not be able to access anything apart from the user's home directory.
For WordPress sites, updating/installing new plugins won't be an issue since it would be run by php-fpm which is running using the user for that directory, so it will be able to replace/add new files on the filesystem.
To even increase the security a bit, we can chmod 600 to the config files containing database information, so no db access to even the group(just to be safe)
For security, php-fpm is never going to have an php-fpm pool with www-data user, otherwise it would jeopardise the whole operation.

**Comment by harshadyeola** [comment]
@gagan0123 

Thanks for the Algorithm!!!

**Comment by gagan0123** [comment]
@harshadyeola 

Happy to be of help :smile:

**Comment by apag96** [comment]
@gagan0123 
Nicely done! A dev can get this implemented soon.

**Comment by AbbyNormal** [comment]
Better would be to create a group example-com also, and add www-data user to that group.  And then in php-fpm pool you should set user and group to example-com and example-com so the php process is run under that user and group and socket should have the same owner and group.
In your scenario I don't see what are you using for group setting in php-fom pool...

**Comment by gagan0123** [comment]
@AbbyNormal 

Thats even better :+1: 

Got your point, if we run php fpm with example-com:example-com, it will create new files with the owner example-com:example-com, which will make the files unreadable by nginx. Using the group of the user that issue will be gone, as www-data will be given read permission to the folder via the group it gets added to, and php fpm can run with example-com:example-com

**Comment by MACscr** [comment]
Im really surprised this isnt already the case that the sites are isolated from each other. I would have thought this would have been part of the initial design. Don't you always want to do this when you have multiple WP sites? Definitely dont want all your sites compromised just because one does.

**Comment by andremacola** [comment]
Still waiting for an official solution. When need to add a new custom owner website, I do manually create the php pool, folders owners and nginx configuration.

**Comment by gleert** [comment]
@rahul286 Any news on this?

**Comment by vvaz** [comment]
this would make EE perfect!

**Comment by bigwilliam** [comment]
@gagan0123 Do you have a script made which would automate the scenario you mentioned above?

**Comment by bigwilliam** [comment]
Ironically a site was compromised on my server yesterday, and it spread to every single other site in EasyEngine, including the utility folder `/var/www/22222`. So yeah, I'd really like to have this implemented. For now, I'm writing my own methods to do this, but the struggle is real - sites do get hacked.

**Comment by gleert** [comment]
This is a must have!!

**Comment by MattyLB** [comment]
@ William, I agree and I've held off on a full production release on
EE until this is addressed. In the meantime, do you mind sharing what the
malware was so I can make sure I address it from all directions?

Thank you!

**Comment by bigwilliam** [comment]
Here's a pastebin of the code which gets copied onto the top of each file.

http://pastebin.com/Bjc22WMf

Currently I've stopped nginx, php and mysql until I can get every site cleaned. Luckily I have backups, but it spreads to the clean files within minutes after re-uploading them. So I'm going to try cleaning everything before putting nginx back online.

**Comment by liquidia** [comment]
@bigwilliam .. Did you tried to find out what caused this infection?

1. Are you behind the sever firewall iptables/fail2ban?

2. If it was a wordpress installation. any loosely written plugin caused this issue?

3. Did you scan your server with ClamAv?

3. Did  you check the logs . ? 

I had a similar issue .I fixed it by tracing the ip trying to post and than get some malicious files in my theme and plugins folder . If you check your access logs in real time you might get some clue or trace of infected files location.

Thanks

**Comment by bigwilliam** [comment]
Hi @liquidia,

1. yes
2. most likely
3. not yet
4. yes

I get hundreds of malicious attempts all the time. Various IP addresses always trying to log in to WP or connect via SSH, etc. I run nightly backups, etc. The only way I can see the hack getting in is through WP.

**Comment by sirshurf** [comment]
So what about this option?
Is it ready yet?

**Comment by gleert** [comment]
Please make easyengine a real shared hosting option!

**Comment by AcidRaZor** [comment]
after 2 years of this issue being open I really doubt EE will make this happen. For now i'll do my own script and if it's okay to be consumed by the public, i'll publish it in my github

**Comment by bigwilliam** [comment]
Hi @AcidRaZor - I wrote my own script for this as well but I haven't shared it yet because it is specific for the stack I'm on. I'd love to combine forces and see if we can come up with something - maybe write a plugin as well since that is a new feature for EE.

The thing is, right now if I set up multiple php pools, I'm not sure if it will work with redis or fast-cgi cache - the way EE is set up. I haven't had time to look into it further as I've been preoccupied with other things.

**Comment by sirshurf** [comment]
I would like to join and help too... Right now My changes to it are inconsistent with EE scripts so when an update is run, I need to change it again... and this is not something I like

**Comment by AcidRaZor** [comment]
I prefer not to base anything off of EE in case there are security issues. Reckon when/if I'm ready to release something, I'll let you guys know and we can collaborate further. Software often gets bloated by unnecessary stuff which opens up a can of worms when security is concerned. A lot of people may be using EE to add websites easier and there is function for this, but in my opinion all of the sites that have been setup by this software are subject to a hack taking down and making vulnerable everything on the server since the creators doesn't think it's worth their time to add this feature and suggest chrooted sftp when they have no clue that a vulnerability in PHP can affect all sites hosted on a server

**Comment by sirshurf** [comment]
Well.... Just your luck... pagespeed security issue and there is no way to update EE... :(

**Comment by MattyLB** [comment]
Has a #poll been taken on this issue yet? In lieu of adding any new tools
or features, I believe we should address this first.

I've been a fan of EE since almost day 1 but this has been a growing
concern of mine and now I basically have to host each site on a separate
vm, which defeats the end purpose of EE.

Please make this a top priority, even if it requires a paid version to help
offset dev costs - if that has been the reason it is on the back burner.
I'm personally willing to pay up to $10 USD per server for a secure CLI
version of EE, and more for an advanced version with an admin/client web
interface.

Thank you in advance.

**Comment by apag96** [comment]
Same here. If this is a feature that will only be added as a 'premium'
addition, I would happily pay for it.

**Comment by gleert** [comment]
+1 If this is a feature that will only be added as a 'premium'
addition, I would happily pay for it.

**Comment by aronwp** [comment]
I’ve been hoping for pools since the start of EE. I have many servers and setup the sites on pools most times or separate servers. In my opinion server security is not a one script fix since there are many situations where security needs to differ per server. But pools are a must have. Hopefully 
https://github.com/rahul286
 or @
https://github.com/MiteshShah
 can chime in on this request.

aronwp

On Thu, Apr 07, 2016 at 11:16 AM gleert

<
mailto:gleert <notifications@github.com>
> wrote:

+1 If this is a feature that will only be added as a 'premium'

addition, I would happily pay for it.

**Comment by bigwilliam** [comment]
Another advantage of running separate PHP Pools is that you can see which site/pool has been using CPU time. Right now all I see is one pool 'www-data' and I don't know which site is the resource hog: screenshot [http://d.pr/i/1iJrB](http://d.pr/i/1iJrB). 

On another serve where I DID set up separate PHP pools manually, I can see the separation. Screenshot: [http://d.pr/i/11RpB](http://d.pr/i/11RpB)

**Comment by andremacola** [comment]
Apparently EasyEngine is left behind. Just create a user, a php pool manually and assign them to the nginx website conf.

**Comment by andremacola** [comment]
For those who want a manual solution: 

https://www.digitalocean.com/community/tutorials/how-to-host-multiple-websites-securely-with-nginx-and-php-fpm-on-ubuntu-14-04

**Comment by dtbaker** [comment]
Can somebody please post a how-to? I'd like to run with EasyEngine and give clients full admin access to individual WordPress installs on subdomains ( e.g. `user1.mysite.com`, `user2.mysite.com`, etc..)

As we know a WordPress admin can upload PHP code in many different ways ( themes, plugins, template editor, etc.. ) and if they're all running as `www-data` then it would be very easy for one user to access the database details in `wp-config.php` of another user. 

I'd like to have each subdomain run as a different user, as discussed in this thread.

Has anybody automated this? Is there an nginx template or something in EasyEngine where I can change some template config values and it will apply to all new sites I create? 

Is the article @andremacola mentioned last year still relevant? 

Or should I be looking at something like CloudLinux?

**Comment by gagan0123** [comment]
Here's a proof of concept I build earlier, forgot to share it, 
https://github.com/avistu/shared_engine
This is a custom script just showing how its possible to add the support for multiple users, use at your own risk.
There are certain other changes I've made to the server where I've implemented this, like default file and directory permissions changed to 650 and 750 respectively.
The structure I've used is much similar to what WHM uses.

**Comment by MiteshShah** [comment]
@gagan0123 Thanks for your project

At [AnsiPress](https://github.com/AnsiPress/AnsiPress)  we does not use shared PHP process to avoid security issue.

Instead of this we create per user separate PHP master process.
service php7.1-mitesh restart
service php7.1-gagan restart 

Where `mitesh` & `gagan` is username

We allocate each user a separate php master process and pool number.

@gagan0123 I'd first tested similar solution which you developed but using that solution 
`mitesh` can upload custom php files which can be read the `gagan` user wp-config.php file easily.

Refer - https://github.com/AnsiPress/AnsiPress/issues/24

**Comment by rahul286** [comment]
@gagan0123 and @MiteshShah by any chance - have you explored Docker-based or some container-level isolation for shared hosting needs?

We haven't reached the final stage of our research yet but Docker seems to handles these problems gracefully. But as you may be already aware, we as a company do not have shared hosting use-case. We are experimenting with Docker to "bundle" a single site as a different entity.

@mbtamuli has more details about Docker-based setup.

**Comment by MiteshShah** [comment]
@rahul286 Nope I'm not used Docker much :(

@mbtamuli @rahul286 I guess You can check [AnsiPress](http://github.com/AnsiPress/) Shared Hosting code and implement it on Docker easily.

FYI - I'll mostly online on https://ansipress.slack.com, 
So if you had any issue or need any help ping me on AnsiPress slack.
Slack invite - http://ansipress.herokuapp.com/

**Comment by harshadyeola** [comment]
@rahul286 
If you want to use docker then there are couple of approaches 
1) combining NGINX & PHP into single container (not recommended)
2) by sharing code volumes from php to NGINX running container. (I found this approach useful)
3) by sharing host volume with NGINX and PHP containers. (this restricts from scaling application to multiple hosts)
I will write and share tutorial on this soon.

**Comment by janiosarmento** [comment]
I hope EE doesn’t go towards Docker for any reason/usage.

Just an user opinion, for what it’s worth.

**Comment by rahul286** [comment]
@MiteshShah 

In Docker-based approach, separation "seems" easy. Maybe you can check with @harshadyeola's method number 2.  

@harshadyeola 
> by sharing code volumes from php to NGINX running container. (I found this approach useful)

I love this approach. Please share more info if you have.  :-)

What are you using for MySQL? Remote DB server or separate container with its own data volume?

For shared hosting, we also thought of adding https://github.com/jwilder/nginx-proxy

And also give direct SSH access via port mapping to their own container. 

@janiosarmento we are exploring Docker and anything this big will take a lot more time. Even if we add docker or anything, the easiness will remain as it is. That being said, can you please help me understand your experience with docker? Is there anything you found that is particularly bad.

**Comment by harshadyeola** [comment]
@rahul286 
> What are you using for MySQL? Remote DB server or separate container with its own data volume?
Currently I prefer remote MySQL.

**Comment by rahul286** [comment]
Makes sense. But for shared hosting setup, we might need to provide an option to run MySQL in same VPS.

**Comment by janiosarmento** [comment]
I had some bad experiences with Docker because it demands a learning time I
didn’t have.

My main trouble was mounting volumes outside the container, accessing logs,
and so on.

I didn’t try any WordPress Docker approach because of previous bad
experiences with other softwares.

**Comment by rahul286** [comment]
@janiosarmento Completely agree on the learning curve!

A reason we haven't added anything related to Docker yet in EE is that after more than a year-long testing and experiments, we are not able to finalize our workflow! :(

So unless we document how we plan to use docker, and open it for feedback, there is no way, it's going to be part of EE core - https://easyengine.io/docs/development-lifecycle/

**Comment by ingobaab** [comment]
@MiteshShah @gagan0123 @rahul286
Did anyone evaluate the pro and cons between using different pools versus per user separated PHP master processes? As far as I understand, APC/Opcache are hold in shared memory per master, so I ask myself, what is better for a shared environment if you have a lot of sites? Should we go with different pools or better with a lot of master-processes? As I googled around, I found restarting php-master-processes is not very 'gracefully' (a long lasting php bug..). Any suggestions from you? Thanks a lot for any comment..
_____
https://bugs.php.net/bug.php?id=60961
https://ma.ttias.be/a-better-way-to-run-php-fpm/

**Comment by MiteshShah** [comment]
@ingobaab The PHP bug was reported for PHP 5.3
I'm not sure PHP 7.1 was affected due to that bug or not.

AFAIK - When we use same PHP master process and create new pool per website it's still all PHP process owned by `www-data` master process and its make all website read other users config file easily.

Refer - https://github.com/AnsiPress/AnsiPress/issues/24

I'd first created and found that user1 can easily read user2 wp-config.php file :(
For you information in my testing user1 and user2 run on different PHP pool and still read each other wp-config.php file easily

Refer - https://github.com/AnsiPress/AnsiPress/blob/fa1e0a8c6a1cb411571797f7f5225ac5f230dc9f/roles/website/tasks/php.yml#L107

To fix this basic security issue separate PHP master is much better option instead of 
1. chroot PHP
2. separate PHP pool with a single master process.

**Comment by ingobaab** [comment]
Hi @MiteshShah, 

thank you for your answer, but I think you are wrong. I testet with different pool-users and I was not able to read anything from another users htdocs directory. In your example you are copying wp.com's "wp-config.php" to php.com's directory and then `chown`-ing all files to `php:php` - what do you expect. If your PHP-Process (master or pool does not matter) runs as  `wp:wp` it could neither copy this file nor change its ownership. Or I am wrong here?

PS: Are you going to WordCamp Europe (June 15-17)? https://2017.europe.wordcamp.org/tickets/

**Comment by MiteshShah** [comment]
@ingobaab Here is my basics/testing ideas

NGINX - www-data
user1 - user1:user1 on php pool 9011
user2 - user2:user2 on php pool 9012

Now we had two websites

/home/user1/vhost/user1.com owned by user1:user1
/home/user2/vhost/user2.com owned by user2:user2

In order to nginx read file we need to add nginx user `www-data` to `user1`  `user2`

Now Lets test:

```
vim /home/user1/vhosts/user1.com/htdocs/read.php
<?php
echo file_get_contents('/home/user2/vhosts/user2.com/wp-config.php');
?>
```

Open `user1.com/read.php` and if you see user2 wp-config.php we need to fix that security issue.

@ingobaab Here is my basic idea, I'll test above settings once I'll in front of a laptop and update you soon!
If you are free you can test above settings and let us know what you think.

**Comment by MiteshShah** [comment]
**Users & Groups:**

```
root@AnsiPress:~# id www-data 
uid=33(www-data) gid=33(www-data) groups=33(www-data)

root@AnsiPress:~# id user1
uid=1001(user1) gid=1001(user1) groups=1001(user1)

root@AnsiPress:~# id user2 
uid=1002(user2) gid=1002(user2) groups=1002(user2)
```

**Permissions**
```
root@AnsiPress:~# ls -lah /home/
drwxr-xr-x  3 user1  user1  4.0K May  8 09:34 user1
drwxr-xr-x  3 user2  user2  4.0K May  8 09:37 user2

ls -lah /home/user*/
drwxr-xr-x 3 user1 user1 4.0K May  8 09:34 vhosts
drwxr-xr-x 3 user2 user2 4.0K May  8 09:37 vhosts


root@AnsiPress:~# ls -lah /home/user*/vhosts/*
/home/user1/vhosts/user1.com:
total 28K
drwxr-xr-x 6 user1 user1 4.0K May  8 09:36 .
drwxr-xr-x 3 user1 user1 4.0K May  8 09:34 ..
drwxr-xr-x 2 user1 user1 4.0K May  8 09:34 conf
drwxr-xr-x 5 user1 user1 4.0K May  8 09:36 htdocs
drwxr-xr-x 2 user1 user1 4.0K May  8 09:34 logs
drwxr-xr-x 2 user1 user1 4.0K May  8 09:34 ssl
-rw-r--r-- 1 user1 user1 3.0K May  8 09:36 wp-config.php

/home/user2/vhosts/user2.com:
total 28K
drwxr-xr-x 6 user2 user2 4.0K May  8 09:38 .
drwxr-xr-x 3 user2 user2 4.0K May  8 09:37 ..
drwxr-xr-x 2 user2 user2 4.0K May  8 09:37 conf
drwxr-xr-x 5 user2 user2 4.0K May  8 09:38 htdocs
drwxr-xr-x 2 user2 user2 4.0K May  8 09:37 logs
drwxr-xr-x 2 user2 user2 4.0K May  8 09:37 ssl
-rw-r--r-- 1 user2 user2 3.0K May  8 09:38 wp-config.php
```

**PHP POOL**
```
 /etc/php/7.1/fpm/pool.d/user1.conf 
user = user1
group = user1
listen = 127.0.0.1:9011;


 /etc/php/7.1/fpm/pool.d/user2.conf 
user = user2
group = user2
listen = 127.0.0.1:9012;
```

**Test read.php**
```
 root@AnsiPress:~# cat /home/user1/vhosts/user1.com/htdocs/read.php
<?php
echo file_get_contents('/home/user2/vhosts/user2.com/wp-config.php');
?>
```

<img width="544" alt="screen shot 2017-05-08 at 3 13 28 pm" src="https://cloud.githubusercontent.com/assets/1223371/25798985/ec9e1f1a-3400-11e7-88bb-f609f29db33e.png">

**Comment by MiteshShah** [comment]
@ingobaab I'd created read.php file under user1 and still its read user2 wp-config.php files.
Let me correct If I'd miss anything here.

**Comment by rahul286** [comment]
v4 already has php process isolation and webroot isolation.

Only thing remaining is giving FTP access per site. I am closing this issue as we FTP related discussion will be separate.
