### ISSUE TITLE
ajenti - web interface

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/easyengine#278]
https://github.com/Eugeny/ajenti/ looks clean and nice

Not sure how it compares against webmin

**Comment by vchanakoski** [comment]
Hi guys

Please keep easyengine as simple as possible, its a bad idea to bloat it. There are a lot of things that need to be enhanced or fixed already.

**Comment by cm896** [comment]
A simple admin stack switch wouldn't add bloat for those who don't want to install it.  I can think of times while AFK that it would have been nice to use these tools remotely via web, instead of ssh'ing into the box to make an urgent change for a client.  I can install this myself in 22222 in problems, but setup during installation with the switch is a nice option, as well as some other admin tools mentioned before, like the log tools, goacess or pimpmylog.  I think building out that side of ee is what provides value for the sysadmin.  Value for the end user is a clean running nginx server (with WP in most cases), but the sysadmin needs to maintain, manage, analyze and tune the server periodically, right?  Making that role easier leads to more secure, healthier servers, and happier clients, no?

**Comment by vchanakoski** [comment]
not really, first of all they will loose more time on unnecessary things, another thing is that these panels have security holes which often are not very promptly fixed as these are side projects. It doesnt always mean the more options the better, for now i am hoping that they will concentrate on the core functionality and ironing it out without loosing time on unnecessary thing. Ajenti has a one line install script if you really need it but i am strongly against wasting time on it.

**Comment by MattyLB** [comment]
A very big +1 to @vchanakoski. Solidifying the current ee stack and
processes should be priority number one before adding more bloat and
features we could easily add via WP itself or a separate, paid offering
from rtCamp down the road. Keep It Simple and Solid (#KISS)

**Comment by w33zy** [comment]
Here's another +1 for keeping EE focused, simple and solid. These recommendation for new additions to EE is how the slippery slope of 'feature creep' starts.

**Comment by michacassola** [comment]
And aside from the bloat argument: Ajenti is not in development anymore! I have been in contact with Eugeny a long time ago and he will not develop it anymore and last I checked there are not adopters. While Webmin is being actively developed...

What would be the things you would like to display in a webpanel @rahul286 ?
I thought our tools are going to be at domain.com/ee-admin/ ?

**Comment by rahul286** [comment]
We will re-review web interface options considering docker has different options.

In any case, this won't be part of the core and will be handled via EE Package.
