### ISSUE TITLE
Testing Redis for object-cache support

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/easyengine#351]
Plugin: https://wordpress.org/plugins/wp-redis/

Please note that this is dropin plugin.

We need to check how redis works as object-cache instead of using w3tc's memcache for object-cache and database-cache.

This Redis plugin provides only object cache. We need to disable w3tc's memcache for object-cache first. 

Also, we may disable w3tc's memcache for database-cache. _(Personally, I always felt that database-cache feature of w3tc is somewhat misfit)_

I don't see any independent database cache plugin actively developed - https://wordpress.org/plugins/db-cache-reloaded/ and https://wordpress.org/plugins/db-cache-reloaded-fix/ are both outdated.

We can start testing on our sites first. If this works, we can add it to main EasyEngine in future.

**Comment by rahul286** [comment]
For manual setup: https://rtcamp.com/tutorials/wordpress/redis-wordpress-object-cache/
https://rtcamp.com/tutorials/php/redis-php-sessions/

**Comment by pjv** [comment]
my redis object cache recently got to the limit of how much ram i allowed it to use and using the default settings in redis.conf i started seeing problems in wordpress. first issue i saw was that people couldn't sticky and unsticky posts. the solution i found was to change the `maxmemory-policy` from the default `volatile-lru` to `allkeys-lru`. this seems to have fixed the sticky issue.

to test, you can change it on the fly without restarting the redis-server by doing:

`redis-cli config set maxmemory-policy allkeys-lru`

if all seems good make the same change in `/etc/redis/redis.conf`

**Comment by rahul286** [comment]
Thanks for suggestion. :-)

On a customer site, we has some WooCommerce cart/session related issue with redis object-cache.

**Comment by pjv** [comment]
i saw the same in tests, so i am unfortunately not running redis object-caching on my WC sites. but i would like to, so if you figure out how, make a big announcement.

i assume that it would require a plugin that does something similar to what W3TC does in the object-cache section where you can exclude certain things from being put in the cache. i also assume that someone smart enough with WP and WC internals could hack the object-cache.php file to exclude WC stuff, but i don't have that knowledge.

**Comment by solhuebner** [comment]
You should consider this plugin https://wordpress.org/plugins/redis-cache/ as it is better supported and is constantly updated  :-)

**Comment by solhuebner** [comment]
And for PPA you should change to https://launchpad.net/~rwky/+archive/ubuntu/redis add the other one is lacking regular updates

**Comment by pjv** [comment]
Hey @solhuebner thanks for calling those out. I will give both a try. I did originally try that redis cache plugin when i first deployed redis, but at the time, I had problems with it, I think because I am running under HHVM. You can see my support thread with the author [here](https://wordpress.org/support/topic/high-cpu-use-with-dropin-installed). But I see that he has since incorporated support for the HHVM redis extension, so I will definitely give it a try again.

**Comment by solhuebner** [comment]
Hi @pjv please post how it works :-)

**Comment by pjv** [comment]
I installed both the [redis cache plugin](https://wordpress.org/plugins/redis-cache/) and the rwky PPA on my production server. Both seem to be working fine. The CPU usage issue that I had originally experienced with an earlier version of the wordpress plugin is gone. Server seems happy. Sites seem responsive.

**Comment by solhuebner** [comment]
Thank you for the update :-)

**Comment by solhuebner** [comment]
@rahul286 did you manage to fix the WC issues?

**Comment by rahul286** [comment]
Thanks @solhuebner and @pjv for sharing your knowledge. :-)

We will try @solhuebner's solution manually on few servers and if all goes well, add it in EE core.

**Comment by rahul286** [comment]
@solhuebner I never had any issue with WC and object cache so no idea about it. It seems @pjv ran into issues with WC. 

@pjv did new solution work well on WC sites?

**Comment by pjv** [comment]
>@pjv did new solution work well on WC sites?

I haven't tried object caching on my WC sites since the original problem. Mostly because I don't really feel like I have enough technical understand of what is being cached when, where, and how so I am stuck with doing trial and error and I hate that. 

If I have a chance, I'll give this setup a try on a test WC site and report back.

**Comment by pjv** [comment]
Preliminary good news: on the test WooCommerce server, I'm not having trouble with redis object caching using the new object cache plugin. My recollection is that there were shopping cart collisions when I originally tried it some months ago. One person would put five things in their cart and those five things would show up in someone else's cart. Very bad. But I installed the plugin and set everything up on the test server and then started making carts in 3 different browsers, putting stuff in, taking it out, moving all around the site, and I had no collisions and no problems of any kind.

So sometime when it looks like a good time, I'll give it a go on one of my production WC client sites and see if it works properly under real load. Would be nice to have object caching on the WC sites again.

**Comment by rahul286** [comment]
@pjv thanks for sharing your result :-)

I came across another plugin today - https://wordpress.org/plugins/cache-buddy/ which really help us speed up buddypress sites. Some user reported speed increase for other non-buddypress "membership" sites. 

If you have a buddypress or other membership site, where logged in users are making caching difficult, try https://wordpress.org/plugins/cache-buddy/ (I guess it works with object-cache only)

**Comment by pjv** [comment]
i tried cache buddy on one of my sites that really needs it badly and should be the exact use-case that cache buddy was made for (according to mark jaquith); it is a site that gets a lot of traffic from many users who comment extensively. it's not a buddy press site, just standard WP but the comment system is used extensively. so most of the users of the site are either logged in as contributors, or have a wp comment cookie, which makes our wonderful nginx fastcgi cache useless and makes my server work very hard on this particular site.

unfortunately, the plugin didn't work right on the site and because i have so much traffic there and the users were freaking out, i couldn't leave the plugin activated long enough to figure out what was going on. i raised an issue in mj's github repo. if i get a chance i will also try to figure it out - it could have just been a theme conflict or something like that.

**Comment by rahul286** [comment]
@pjv I just saw - http://www.slideshare.net/markjaquith/scaling-wordpress-15441095 

I think that plugin makes many assumptions and a plugin/theme conflict is last thing it can tolerate.

Overall the idea is nice and I will test it on some client site. If all goes well, we may add it in EE at some point. :-)

**Comment by pjv** [comment]
yeah, i think it's a great idea to use some javascript to fill in little bits of dynamic content on a page where possible in order to make a full page cache workable for logged in users. i wonder if it could be generalized beyond just the comment form. 

but it definitely didn't work in my environment as-is. logged in users did not have the comment form pre-filled with their information. my current guess is that the theme we are using probably just isn't compatible with whatever DOM element targeting the plugin uses. if that's all the problem is, should be easily solved. when i have some time, i'll take a look at it.

**Comment by rahul286** [comment]
Yep. Theme can break comment form.

**Comment by rahul286** [comment]
This can be discussed further in #472
