### ISSUE TITLE
Build letsencrypt.org in Next Version

### ISSUE THREAD

**Issue by tinbot-development** [EasyEngine/easyengine#376]
I think it would be awesome if EE could automatically set up TLS for all sites when configuring the domain.

**Comment by rahul286** [comment]
Related to #303

**Comment by jnimmo** [comment]
Tagging Lets Encrypt Let's Encrypt for searchability

**Comment by rahul286** [comment]
Note: https://github.com/OpenVPN/easy-rsa

**Comment by dimadin** [comment]
Now that Let's Encrypt is close to general availability, maybe it's time to think about how it should be included in EE.

My thinking goes to something like this:
 * add command `--https` used when creating site that
   * gets certificates for both www.example.com and example.com and adds Nginx rules to use them
   * adds Nginx rules that redirect HTTP to HTTPS (because I don't think there should be option and mixing, like it is for www)
    * enables HTTP/2 when available
    * uses that certificate for EE Admin
    * uses it in options when setting up WordPress.

I am not sure what to do with existing sites or with `--wpsubdomain` (I have never used that command).

Also it should be noted to take care about servers that might already install Let's Encrypt before EE supports it (for example, I plan to play with it).

For the record, I think that this thread can be useful reading:
https://community.letsencrypt.org/t/completely-automated-setup/3121

**Comment by jnimmo** [comment]
Sounds good, I would suggest --letsencrypt perhaps in keeping with the theme the other commands like pagespeed use the actual product name..
Other considerations 
- It should enable ssl stapling
- It could run with --wpsubdomain sites but only for the primary domain
- Why not make it the default for new sites to install a certificate unless otherwise specified, especially for Wordpress sites

**Comment by oviliz** [comment]
+1

**Comment by dimadin** [comment]
Good idea on `--letsencrypt`, didn't think about that.

**Comment by w33zy** [comment]
@jnimmo the letsencrypt option should not be a default. I have many clients who run websites that are funded by ads. A lot of these ad networks don't only serve ads by 'http'. Its kinda sad but the most popular ad network used by food bloggers say "'https' ads are not a priority right now". 

A big YES to LetsEncrypt but it ought to be optional.

**Comment by jnimmo** [comment]
Agree of course it should be optional but in my opinion it should be turned on by default for new WP installs, a few versions down the track. Just because ad companies haven't caught up doesn't mean by default the security of all other EE users should be weakened by default. Of course this would be up to EE anyway. My argument is that it simply isn't safe ever to log into WP admin not over HTTPS.

**Comment by dimadin** [comment]
And it's finally available to anyone: https://letsencrypt.org/2015/12/03/entering-public-beta.html

**Comment by kymcarlsson** [comment]
Here's a cool walkthrough for anyone who missed it: https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-14-04

**Comment by iam404** [comment]
EasyEngine 3.4.0 with HTTP/2 and Lets Encrypt support is in Beta phase.
Please check this for v3.4.0-beta installation instructions https://easyengine.io/docs/beta-testing/
