### ISSUE TITLE
Rocket-Nginx for WP-Rocket

### ISSUE THREAD

**Issue by thedevly** [EasyEngine/easyengine#533]
We should take a look at https://github.com/maximejobin/rocket-nginx for guys who are using WP-Rocket.
I tested it on EE and works fine ! Needs some tweaking but definitely works

**Comment by cm896** [comment]
What ee site create command did you use to create your site?
Are you using --wpfc or any additional methods --pagespeed --hhvm - etc...?
I am wondering if I can try this out for my troubled site.

If I drop these two includes in favor of this rocket-nginx.conf include.
	include common/wpfc.conf;
	include common/wpcommon.conf;

WP-Rocket.me include
https://github.com/maximejobin/rocket-nginx/blob/master/rocket-nginx.conf

I'd need to push in the SEO stuff for yoast - did you make any modifications to this conf to accomodate?

**Comment by doringheorghe** [comment]
Actually I'm playing around with EE. I have HHVM + Redis + php5-fpm as fallback, nginx with fastcgi_cache.
As cache plugin I'm using WP-Rocket. I tweaked nginx to work fully with rocket-nginx configuration.
PageSpeed I'm not using because it has some issues with cache (as I understand its in the works).
So --wpfc --hhvm :)
Also besides nginx-helper and wp-rocket, I'm using Redis Object Cache plugin, that i found its the best outhere.

**Comment by cm896** [comment]
Great - and no issues with the redis object cache plugin and wp-rocket plugin.  I might give this a try in the near future.  Thanks for the tip.

**Comment by brianjking** [comment]
@thedevly What changes did you have to make outside of those mentioned on the Rocket Nginx readme? Thanks!

**Comment by rahul286** [comment]
Sorry for a delayed update here.

We have decided to keep only one caching backend in EE v4 so this is something we won't be able to consider any further.
