### ISSUE TITLE
redis plugin give a lot of 104: Connection reset by peer

### ISSUE THREAD

**Issue by caclement** [EasyEngine/easyengine#599]
On a fresh install on Debian 8x64 with --wpredis, certain popular plugins wont work with object cache activated.

So far wpml and formidable pro pages are giving me errors like this :

2015/08/04 16:58:55 [error] 4707#0: *266 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: XXXXX, server: test.com, request: "POST /dons/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "test.com", referrer: "http://test.com/dons/"

If I deactivate redis object cache, it will work perfectly.

For wpml, I get those errors when I try to update a translation.
For formidable pro, I get those errors when I try to create a form, view records, or submit a record.

**Comment by clakeb** [comment]
I'm getting the same thing with Formidable Pro. Obviously, I should be using GF but this is a client site. Anyways...just thought I'd acknowledge I'm getting the same thing.

**Comment by MattyLB** [comment]
I hate to say it, but when the survey was first put out by the EE team
about redis vs memcache, I did my homework and concluded that
native memcache was the better option because of limitations in
redis pointed out by Pinterest and many others, not to mention you can't
run an ssl site with redis unless you jump through hurdles. In summary,
DUMP REDIS and DUMP W3TC plugins because they're either bloated,
fundamentally incompatible with many tasks we're trying to accomplish, or
more importantly, they're just not up to speed with where we are trying to
go with our sites. It takes more than a village to make a unique site work,
and sometimes asking for too many built in features to an otherwise
amazingly simple site building platform (EE) defeats every purpose that
made us fans of the platform to begin with. My advice for the team is
to FOCUS on what is fully supported by the WP team and make it easy enough
for us to "tinker" with new features on our own with a backup repository
for when we mess up royally and need a simple cli command to go back as we
spank ourselves.

**Comment by adamesss** [comment]
I have to agree with you Matty redis is a complete nightmare without putting too finer point on it, I really think that ee to be the best of the best needs to go back to basics, with simplicity and to aim for compatibility and sensibility + stability.

**Comment by rahul286** [comment]
Sorry for a delayed reply. I hope your issue is fixed by now.

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
