### ISSUE TITLE
Error when creating new site 2003, "Can't connect to MySQL server on 'localhost' (111)

### ISSUE THREAD

**Issue by juninho14** [EasyEngine/easyengine#615]
Im having this error everytime i try to create a new website.

2003, "Can't connect to MySQL server on 'localhost' (111)

Anyone knows how can i fix it?

**Comment by MiteshShah** [comment]
@juninho14 Did you change mysql root user password?

By default ee reads mysql root user password from ~/.my.cnf file.
If your ~/.my.cnf file is correct then you can directly login into mysql shell using following command

```
[mitesh@shah ~] $ mysql
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 1030318
Server version: 10.0.21-MariaDB-1~precise-log mariadb.org binary distribution

Copyright (c) 2000, 2015, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>
```

**Comment by harshadyeola** [comment]
@juninho14 
Can you please your server listentening on specific ip, You need to put that in your `.my.cnf`
reference http://stackoverflow.com/questions/1420839/cant-connect-to-mysql-server-error-111

**Comment by rahul286** [comment]
@juninho14 Sorry for a delayed reply. I hope your issue is fixed by now with the help from @MiteshShah and @harshadyeola .

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
