### ISSUE TITLE
While installing it only check user specific git config & not the system level

### ISSUE THREAD

**Issue by pradeepbishnoi** [EasyEngine/easyengine#645]
Assuming you do not have Git configuration done for a specific user (~/.gitconfig) however it is done at system level in /etc/gitconfig file. 

Try installing EasyEngine from your Terminal...

```
wget -qO ee rt.cx/ee && sudo bash ee
```

and it will ask for to "Enter Username" & "Enter Email", to be used for setting up your GitConfig.

Ideally, the check should be done for following files (in same sequence) as `git config` does it.
- /etc/gitconfig
- ~/.gitconfig    OR   ~/.config/git/config
- .git/config  (not applicable, as we won't have the git repo yet)

Refer https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup

Content of my /etc/gitconfig file

> [user]
> name=Pradeep Bishnoi
> email=pradeep.bishnoi@gmail.com

On running `git config -l`, it shows 

> user.name=Pradeep Bishnoi
> user.email=pradeep.bishnoi@gmail.com

**Comment by rahul286** [comment]
Sorry for a delayed reply. We will unlikely to handle this in v3 but we will brainstorm about how this should be handled in v4.

**Comment by mbtamuli** [comment]
In my opinion instead of depending on Git config, we should use the EasyEngine configuration itself. This way, you can specify global as well as local config and you can have all config in a single location (EasyEngine config)

Arguments are interpreted following an order of precedence, from highest priority to lowest:
 * Command-line arguments.
 * `ee.local.yml` file inside the current working directory (or upwards).
 * `ee.yml` file inside the current working directory (or upwards).
 * `~/.ee/config.yml` file (path can be changed by setting the **EE_CONFIG_PATH**  environment variable).
 * EasyEngine defaults.

**Comment by mrrobot47** [comment]
The current implementation is explained in the above [comment](https://github.com/EasyEngine/easyengine/issues/645#issuecomment-402095302). Closing this issue now as in v4 it does not ask for this prompt while installation and required parameters like mail id for letsencrypt can be set in the config files as mentioned above or can be passed using global parameters.
