### ISSUE TITLE
PHP7 Support?

### ISSUE THREAD

**Issue by irazasyed** [EasyEngine/easyengine#649]
PHP7 is set to be released on 3rd Dec or anytime soon. Are you guys planning to update EE to support this upgrade or it can just be done with the existing commands?

**Comment by gau1991** [comment]
PHP 7 support is added once it is released as stable.

**Comment by irazasyed** [comment]
It's released as stable now - http://php.net/archive/2015.php#id2015-12-03-1

**Comment by jfschubert** [comment]
+1

**Comment by datagroove** [comment]
+1

**Comment by MattyLB** [comment]
If any of you are following the php project on github, you'll see
they're scrambling to fix several issues - many of which pertain to php 7
running on certain VM servers. Either way, EE could still release it with
the same "experimental" confirmation they use for HHVM and REDIS and all
should be good because these issues are being actively addressed and won't
affect everyone. (just a word of caution) =)

+1 from me now

**Comment by MattyLB** [comment]
Just an update on an important php7 issue that is resolved now and directly
affects php-fpm: https://github.com/php/php-src/pull/1638/files.

This and other VM, OpenSSL, general typos and glitches in the initial
release are being mended and I would love to see at minimum an EEB (beta)
set created for us to test PHP7 with Nginx1.9.7x if at all possible. Maybe
going forward this EEB solution could be the non-production way of testing
new solutions or creating DEV environments that could then be migrated to a
production EE environment.

Thoughts?

**Comment by irazasyed** [comment]
Agree ^

EEB sounds good. +1
