### ISSUE TITLE
Local wordpress with remote db very slow

### ISSUE THREAD

**Issue by milothemeadmin** [EasyEngine/easyengine#655]
Hi,
I have problem when running code from localhost.
- I have source code on server and localhost(they have same source and same database)
- However if I use source from server via this link:
  dev.xxxx.com. the site run very fast (about less than 2s)
- If i use source from localhost by add this code in host file:
  127.0.0.1 dev.xxxx.com (it will use source from local)
  the time run from 2s to above 15s. I don't know the reason. Hope you can help us.
- I have attached image problem when run our site when use source from localhost. It got 15s pending before load site.
  Thanks you!
  ![loadpage](https://cloud.githubusercontent.com/assets/16218394/11831508/6f80856e-a3e1-11e5-8b1d-6756c44586b3.png)
  ![pending](https://cloud.githubusercontent.com/assets/16218394/11831509/6f87264e-a3e1-11e5-9cba-fba373316d20.png)

**Comment by rahul286** [comment]
@milothemeadmin Sorry for a delayed reply.

You may benefit from tips I covered here https://wordpress.tv/2015/07/17/rahul-bansal-debugging-wordpress-performance-using-easyengine/

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.

Please use http://community.rtcamp.com/c/easyengine for future support questions.
