### ISSUE TITLE
WordPress Backup

### ISSUE THREAD

**Issue by Asif2BD** [EasyEngine/easyengine#704]
EasyEngine is already capable for WordPress backup, it automatically performs it when you try any "ee site update" command. It performs a db dump and file backup(now only wp-config and domain's nginx cong file) and put it in /var/www/domain.tld/backup/DayMonthYearTimeStamp

Its very possible to add a full file backup and put a compressed version there too. We could have command like this

ee site backup domain.tld

We could extend the functionality in future with options like

ee site backup domain.tld --files=false
while file, db and config alls are stored by default.

In future there could be cron based automotion like

ee site backup domain.tld --daily
or
ee site backup domain.tld --frequency=monthly

Like that. Seems like very possible to do and will be very helpful.

Regards

**Comment by pnommensen** [comment]
@Asif2BD agreed. And, can be extended to support [S3cmd](http://s3tools.org/s3cmd) and other cloud storage.

**Comment by Asif2BD** [comment]
S3cmd seems super cool and easy to implement. +1 for it.

**Comment by timelf123** [comment]
This should be a priority for EE. Since wp-config file is moved outside the normal dir (a good thing normally), many of the usual plugins for WP backups don't work.

Seems like all that's left is tar/gz the fs and dump the DB for that site? The external s3 stuff can wait until after the core feature is done

**Comment by janiosarmento** [comment]
What’s wrong with mysqldump, tar, gzip stuff?

**Comment by timelf123** [comment]
Nothing -- it should just be wrapped into a convenience method `ee site backup domain.tld` ;)

**Comment by w33zy** [comment]
@timelf123 
Which backup plugins have you come across that has issue with the location of ````wp-config.php````?

**Comment by timelf123** [comment]
To be fair it happened on the first plugin I tried and I gave up and opted for a cli solution. 

I'm fairly sure it was this one https://wordpress.org/plugins/wordpress-backup-to-dropbox/

**Comment by MiteshShah** [comment]
IMHO We have to keep 2 sets of backup.

1. Local Backup - rsnapshot
2. Remote Backup - Duplicity (S3 upload)

Reason to use two different software is due to some unknown bug one backup was failed then we always have backup which was taken by different software.

Also local backup was useful in fast recovery.

**Comment by rahul286** [comment]
Closing this thread as #1045 has better documentation. We will definitely like to have this for our-self.
