### ISSUE TITLE
Error FATAL -> Failed to fork

### ISSUE THREAD

**Issue by DangLongDe** [EasyEngine/easyengine#711]
I'm getting this error at the 
root@server:~# ee site create binhminhphat.com --wpfc --pagespeed
PageSpeed is experimental feature and it may not work with all CSS/JS/Cache of your site.
You can disable it by passing --pagespeed=off later.
Do you wish to enable PageSpeed now for binhminhphat.com?
Type "y" to continue [n]:y
FATAL -> Failed to fork.

I can't creat. Help me, please!!! :'(

root@server:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:        12.04
Codename:       precise

**Comment by leighharro** [comment]
How much free memory do you have left on that machine? May not be relevant but I had similar issue and was simply a lack of free memory to launch the process to execute the command on the VM I was using at the time.

**Comment by rahul286** [comment]
@DangLongDe Sorry for a delayed reply. I hope your issue is fixed by now with the help of @leighharro 

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
