### ISSUE TITLE
redis-php-7.conf sets $skip_cache 0; on POST requests?

### ISSUE THREAD

**Issue by khromov** [EasyEngine/easyengine#724]
Relevant line from `redis-php7-conf`:

```
# POST requests and URL with a query string should always go to php
if ($request_method = POST) {
  set $skip_cache 0;
}
```

Shouldn't `$skip_cache 0` be `$skip_cache 1` ?

Please attach the output of following command when open a new support request.

- [x] lsb_release -a

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
```

- [x] ee -v

```
EasyEngine v3.6.1
```

- [x] ee info

```

NGINX (1.10.0):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1

PHP (5.6.22-2):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001

MySQL (10.1.14-MariaDB) on localhost:

port                             3306
wait_timeout                     600
interactive_timeout              28800
max_used_connections             2
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf
```

- [x] wp --allow-root --info

```
PHP binary:     /usr/bin/php7.0
PHP version:    7.0.7-2+donate.sury.org~trusty+1
php.ini used:   /etc/php/7.0/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI packages dir:    /root/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.23.0
```

**Comment by iam404** [comment]
Hi @khromov 
Thanks for pointing out the issue. We will fix it on next release.

**Comment by harshadyeola** [comment]
@khromov @iam404 
srcache-nginx-module by default does not cache the POST request so keeping above config unchanged will not harm.
Refer : https://github.com/openresty/srcache-nginx-module#srcache_methods

**Comment by khromov** [comment]
@harshadyeola In that case, may I suggest to either remove that directive from `redis-php7.conf` altogether, or set it to `$skip_cache 1;` to avoid confusion?

**Comment by rahul286** [comment]
We will do `set $skip_cache 1;`

**Reason**

Fasctcgi - http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_cache_methods also does not cache HTTP POST requests by default. In fact by default HTTP POST and Query String shall not be cached.

But if anything changes in future, we can avoid surprises by explicitly telling not to cache POST request.

Also, at some point, I want to refactor nginx config files so that all rules like below can we defined in one place and used with different caching mechanism. 

```# POST requests and URL with a query string should always go to php
if ($request_method = POST) {
  set $skip_cache 0;
}
```

This is in line with DRY also - https://en.wikipedia.org/wiki/Don%27t_repeat_yourself

And keeping in line with DRY, if we remove above 3 lines at some point, they will be removed from all config files including fastcgi.

So for now, we will add `set $skip_cache 1;`

**Comment by harshadyeola** [comment]
@rahul286 thanks for nice explaination 👍

**Comment by frederichoule** [comment]
Let's say I DO want to cache POST requests. Is there any way to do this?

Thanks.

**Comment by khromov** [comment]
@frederichoule POST requests are by definition submissions to post information, so caching those would be a really bad idea. Just convert any POST call you have into a GET call.

**Comment by frederichoule** [comment]
@khromov I have a website that doesn't need any kind of POST except on a specific URL, so I rather "cache" those requests to limit possible DDoS attacks that would trigger PHP on every request because it is not cached.

If that can help anybody, adding this line to your nginx.conf will do the job. And make sure you set your $skip_cache variable according to your requirements.

srcache_methods POST PUT DELETE;

**Comment by kymcarlsson** [comment]
It's a shame (and a little frustrating) this was rejected at the time: https://github.com/EasyEngine/easyengine/pull/678
Anyway, glad it made it in eventually.

**Comment by rahul286** [comment]
@kymcarlsson I admit it was a mistake on behalf of us to reject #678 
I apologise for frustation it caused to you.
