### ISSUE TITLE
Custom skip_cache

### ISSUE THREAD

**Issue by lewayotte** [EasyEngine/easyengine#760]
Is it possible to create your own custom skip_cache? For instance, there was recently a commit to add woocommerce_items_in_cart in the http_cookie conditional. But there are a number of other ecommerce solutions for WordPress (EDD, Leaky Paywall, etc). It would be nice if there was a way to add a conf in the site's directory to add their own conditional to skip the cache.

Perhaps just the appropriate conf files could include a skip-cache.conf file in common/ that can be customized and not overwritten on ee update. Of course, this isn't entirely ideal, because it'd be a global for every site on a server, but I haven't found any other way to achieve this.

**Comment by renatonascalves** [comment]
This is how I do in my .conf file

`# Don't skip by default
set $skip_cache 0;

##
#  Woocommerce Pages
##
if ($request_uri ~* "/(apoio|carrinho|finalizar-apoio/minha-conta)/*$") {
  set $skip_cache 1;
}

if ( $cookie_woocommerce_items_in_cart = "1" ){
  set $skip_cache 1;
}

# BuddyPress // bbPress Pages
if ($request_uri ~* "/(sala|estatistica|perguntas/ativacao/turmas)/*$") {
  set $skip_cache 1;
}
`

You could create a file and put your custom skip-cache statements and load it. Save your version for ee updates.

I agree that a custom localization or skip-cache file loading with support for updates would be a good addition to ee, because custom skip-cache are a specific scenario, one should know first how many people actually changes the .conf file to add this.

**Comment by iam404** [comment]
@lewayotte  you can follow the solution provided by @renatonascalves . We do not replace whole .conf file on `ee update` unless there is a major change on file.
If you have any other queries please open a topic at http://community.rtcamp.com/c/easyengine.

**Comment by renatonascalves** [comment]
Just one more thing, the only time I saw/noticed the .conf being updated and removing all my custom skip-cache was when I updated PHP version, from 5.6 to 7. Easyengine updates the whole .conf with the new information and back the old one up.
