### ISSUE TITLE
woocommerce braintree fields not displaying

### ISSUE THREAD

**Issue by jknight2014** [EasyEngine/easyengine#792]
I dont have a ton of info here but I wanted to make the issue known. 

When installing with the --w3tc option woocommerce default braintree plugin has issues showing the hosted credit card field. I could not figure out why this was happening. There were no errors in wordpress, woocommerce, nginx, or the browser. I also had hhvm and php7 enabled. I tried disabling both with no luck. 

I found changing the cache option to wpfc fixed the problem. I could even re-enable hhvm and php7. Changing back to w3tc broke the site again. That is the info I have. I fought this issue for several months before I found this solution. I am running on a ubuntu 16.04 vps.

**Comment by rahul286** [comment]
Sorry for a delayed reply. We are in the process of deprecating support for --w3tc and --wpsc.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.

Please use http://community.rtcamp.com/c/easyengine for future support questions.
