### ISSUE TITLE
WP Cli 0.24.1 incompatible with WP 4.7 

### ISSUE THREAD

**Issue by tersor** [EasyEngine/easyengine#804]
See also: http://wp-cli.org/blog/version-0.25.0.html

**Comment by janiosarmento** [comment]
As a workaround one can simply:

`wp cli update`

**Comment by janiosarmento** [comment]
As a workaround one can simply:

`wp cli update`

**Comment by rahul286** [comment]
@tersor Sorry for a delayed reply. I hope your issue is fixed by now with the help from @janiosarmento 

Today's ee release also updates wp-cli https://easyengine.io/blog/easyengine-v3-8/

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
