### ISSUE TITLE
ee stack restart php7 (debian jessie)

### ISSUE THREAD

**Issue by ddur** [EasyEngine/easyengine#844]
Response: 

> Your platform does not support PHP 7

But I have PHP 7 installed and running.

Do we need to check platform codename here? Service is installed or not-installed.
https://github.com/EasyEngine/easyengine/blob/master/ee/cli/plugins/stack_services.py#L59
https://github.com/EasyEngine/easyengine/blob/master/ee/cli/plugins/stack_services.py#L150
https://github.com/EasyEngine/easyengine/blob/master/ee/cli/plugins/stack_services.py#L241
https://github.com/EasyEngine/easyengine/blob/master/ee/cli/plugins/stack_services.py#L334
https://github.com/EasyEngine/easyengine/blob/master/ee/cli/plugins/stack_services.py#L425

- OS Debian GNU/Linux 8.6 (jessie)
- ee v3.7.4
- ee info: PHP (7.0.14-1~dotdeb)

**Comment by rahul286** [comment]
@ddur Sorry for a delayed reply. I hope your issue is fixed by now.

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
