### ISSUE TITLE
I deleted site to install a wordpress but i got an error

### ISSUE THREAD

**Issue by hamoosh** [EasyEngine/easyengine#845]
When I try to create a wordpress site after I deleted it
ee site create example.com --wp
Nginx configuration /etc/nginx/sites-available/example.com already exists

and when I type ee site list . I can't find it and can't create a new one ?

**Comment by rahul286** [comment]
@hamoosh Sorry for a delayed reply. I hope your issue is fixed by now.

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
