### ISSUE TITLE
Pick an ORM library for EE's SQLite DB and Migrations

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/easyengine#852]
wp-cli doesn't require a database of its own

We would benefit from using an ORM wrapper for EE's SQLite  DB

- [ ] Migration - to manage database changes between upgrades.

**Comment by rahul286** [comment]
Team has done own DB wrapper https://github.com/EasyEngine/easyengine/blob/develop-v4/php/class-ee-db.php

**Comment by rahul286** [comment]
@mrrobot47 how we will handle schema upgrades for DB?

Please refer following from #858 

> Migration - to manage database changes between upgrades. Laravel -  https://laravel.com/docs/5.4/migrations . Outside - https://phinx.org/ looks good.

**Comment by abhijitrakas** [comment]
@rahul286 I found two options.

1) Propel (http://propelorm.org/)
Propel have ORM+Migrations options.

2) illuminate/database (Laravel Orm: https://github.com/illuminate/database)
Laravel Orm is unable to provide migration functionality outside Laravel as it required Laravel framework instance for that. But we can use Phinx for migration with Laravel ORM. (Ref: https://siipo.la/blog/how-to-use-eloquent-orm-migrations-outside-laravel)

**Comment by mbtamuli** [comment]
Since we currently do not have enough data to form an opinion, we'll tackle this issue in the next beta release.

**Comment by rahulsprajapati** [comment]
We have tried few libs for ORM + Migrations and all of them needs some dependency of there framework. And we don't want to add some dendancy of any framework. 

Like: [phinx](https://github.com/cakephp/phinx) - Internally loads cakephp framework ( with core )
Laravel ORM - This also has laravel framework dependency for db connections ( which is obvious ),
[Doctrine](https://www.doctrine-project.org/) uses some symfony package and zendframework as dependency etc.  

And our use in ee4 is not that much we just required SQLite support with few tables, so we are deciding to create our custom ORM + Migration and keep it simple and clear. 

We will keep architecture of migration like laravel / phinx but the code will be custom so that we can easily make modifications.

**Comment by rahul286** [comment]
@rahulsprajapati did you check http://propelorm.org/ ? http://propelorm.org/documentation/09-migrations.html ?

Avoid writing custom codes as ORM + Migration is not a focus area.

> Re: Doctrine uses some symfony package and zendframework as dependency etc.

I did not see zend deps in https://github.com/doctrine/doctrine2/blob/master/composer.json#L18 

Symfony is fine as we might end up using other symfony package as we progress.

**Comment by rahulsprajapati** [comment]
>I did not see zend deps in https://github.com/doctrine/doctrine2/blob/master/composer.json#L18

Yep, the doctrine is not installing zend deps directly. But the package they've used "ocramius/proxy-manager" is using that. https://github.com/Ocramius/ProxyManager/blob/master/composer.json#L21 

And this doctrine lib have dependency of Symfony that was the main reason we dig into this lib since we already have some in our ee v4 core.

---

About the http://propelorm.org/ this lib itself says that it's not stable ( **Never ending alpha** ) and they recommended using Doctrine if we are looking for long term support so if we go with propel we might end up fork this repo and be maintaining this repo. 

>Our advice:
>
>Use Doctrine if you are looking for a long-term supported, full-featured (and difficult to learn) and stable ORM.

ref: https://github.com/propelorm/Propel2#status-of-the-project

Also I see so many issue raised on repo already https://github.com/propelorm/Propel2/issues and seem they're not getting much of contriburions in this as they've mention in readme. 

---

> Avoid writing custom codes as ORM + Migration is not a focus area.

**Comment by kirtangajjar** [comment]
Closing it as it has we've written our custom migration code and chosen to go without ORM.
