### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1932 Table

### ISSUE THREAD

**Issue by naqirizvi** [EasyEngine/easyengine#874]
My server was running fine, When user logged in today it gave an error 
SQLSTATE[42S02]: Base table or view not found: 1932 Table 'dd_name.tbl_users' doesn't exist in engine

I tried many solutions but still no success.
When I log in through phpmyadmin and select any of database it says:
#1146 - Table 'phpmyadmin.pma__tracking' doesn't exist

**Comment by rahul286** [comment]
@naqirizvi Sorry for a delayed reply. I hope your issue is fixed by now.

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
