### ISSUE TITLE
Php Only Site - Default Configs 'Break' 404 Handling

### ISSUE THREAD

**Issue by mwaterhouse** [EasyEngine/easyengine#889]
When you create a php only site using --php7 (i.e. no CMS), these files get included:-
common/php7.conf
common/locations-php7.conf

Both use try_files statements that end up at index.php where files are not found. This is fine for Wordpress but prevents normal 404 handling for a php based site as any page that doesn't exist will just display the homepage.

php7.conf contains:-
```
location / {
    try_files $uri $uri/ /index.php?$args;
}
```
locations-php7.conf contains:-
```
location = /robots.txt {
  # Some WordPress plugin gererate robots.txt file
  # Refer #340 issue
  try_files $uri $uri/ /index.php?$args;
  access_log off;
  log_not_found off;
}
```

**Comment by rahul286** [comment]
@mwaterhouse Sorry for a delayed reply.

You may try changing

```
  try_files $uri $uri/ /index.php?$args;
```

to

```
  try_files $uri $uri/ =404;
```

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.
