### ISSUE TITLE
When HTTPS on : TTFB increases dramatically with each access to resource

### ISSUE THREAD

**Issue by eddr** [EasyEngine/easyengine#927]
Running an Nginx 1.10.3 server on a debian 8.6 and noticed a strange behavior when accessing an image file (or any other big file). The image loads fine, but TTFB (Time To First Byte) increases dramatically with each access to this image, when HTTPS is on and only then. Disabling HTTPS results in a typical performance

The test is done by disabling browser cache and reloading the resource in repeat, using multiple tabs (2-3 suffice to see that problem). Browser cache is disabled via Chrome developer panel.

That's with the default nginx ee configuration. I've tried it on multiple test sites and new Debian 8.6 installation on Linode. Also with Nginx 1.12.

Something with the configuration, installation of related software is wrong. Couldn't pinpoint it at all.

As a comparison, performance on CentOS 7 with centminmod were better.

**Comment by eddr** [comment]
This can be replicated by installing Debian 8.6 on Linode, following ee installation instructions, creating a demo site (even a simple html site), activating HTTPS via LE and trying to access a big resource like an image from multiple tabs at once.

**Comment by rahul286** [comment]
@eddr 
Sorry for a delayed reply. I hope your issue is fixed by now. You may try latest Nginx build we released today https://easyengine.io/blog/easyengine-v3-8/

If you are still facing the issue, please use http://community.rtcamp.com/c/easyengine for further support.

We are cleaning up issue tracker and closing this issue because we won't be able to contribute to this discussion further.

**Comment by eddr** [comment]
Thanks. I'm not exactly sure why this happened and if EE was the source of the problem. Probably not

Anyway, thanks. I'll test 3.8. Happy to see you are on it
