### ISSUE TITLE
Compile easyengine nginx with PageSpeed

### ISSUE THREAD

**Issue by jasomdotnet** [EasyEngine/easyengine#957]
Compile nginx with [PageSpeed](https://www.modpagespeed.com/). Mode PageSpeed makes site fast withou need to accumulate extra knowledge.

From [incubator-pagespeed-ngx](https://github.com/apache/incubator-pagespeed-ngx):

ngx_pagespeed speeds up your site and reduces page load time by automatically applying web performance best practices to pages and associated assets (CSS, JavaScript, images) without requiring you to modify your existing content or workflow. 

There was an [issue](https://github.com/EasyEngine/easyengine/issues/497) with mode pagespeed 2 years ago, is it still actual?

**Comment by VirtuBox** [comment]
Hello,

Pagespeed feature is depreciated since EasyEngine v3.6.
source : https://easyengine.io/tutorials/nginx/using-pagespeed/

But you can still compile nginx and mod_pagespeed with EasyEngine using [nginx-ee bash script](https://github.com/VirtuBox/nginx-ee). 

However, you may encounter some errors if you use Pagespeed with another cache system.

**Comment by jasomdotnet** [comment]
Thank you, I appreciate bash script link.

**Comment by rahul286** [comment]
Thanks @VirtuBox for jumping in. I am closing this issue as we do not plan to look further into this.
